<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="books.xsl"?>
<!DOCTYPE books [
    <!ELEMENT books (book+)>
    <!ELEMENT book (title, author+, isbn, publisher, edition, price)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT isbn (#PCDATA)>
    <!ELEMENT publisher (#PCDATA)>
    <!ELEMENT edition (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
]>

<books>
    <book>
        <title>Effective Java</title>
        <author>Joshua Bloch</author>
        <isbn>978-0134685991</isbn>
        <publisher>Addison-Wesley</publisher>
        <edition>3rd</edition>
        <price>45.00</price>
    </book>
    <book>
        <title>Clean Code</title>
        <author>Robert C. Martin</author>
        <isbn>978-0132350884</isbn>
        <publisher>Prentice Hall</publisher>
        <edition>1st</edition>
        <price>50.00</price>
    </book>
    <book>
        <title>The Pragmatic Programmer</title>
        <author>Andrew Hunt</author>
        <author>David Thomas</author>
        <isbn>978-0135957059</isbn>
        <publisher>Addison-Wesley</publisher>
        <edition>2nd</edition>
        <price>55.00</price>
    </book>
</books>
